spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: update

kakao:
  client-id: "d8f1fcc67fdb21688235edd337d80045"
  redirect-uri: "http://localhost:8080/auth/kakao/callback"

jwt:
  secret: "${JWT_SECRET_KEY}"
  access-token-expiration: 3600000
  refresh-token-expiration: 1209600000

